name: Require Comment on Issue Close

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for closing comment
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          CLOSER: ${{ github.event.sender.login }}
          CLOSED_AT: ${{ github.event.issue.closed_at }}
        run: node .github/scripts/check-closing-comment.js
