name: Require comment to close issues
on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce "comment required" rule
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = context.payload.issue.number;
            const closer = context.actor;
            const closedAt = new Date(context.payload.issue.closed_at);

            console.log('Processing issue #' + issue_number + ' closed by ' + closer);

            const { data: comments } = await github.rest.issues.listComments({
              owner, 
              repo, 
              issue_number, 
              per_page: 20, 
              sort: 'created', 
              direction: 'desc'
            });

            const windowMs = 5 * 60 * 1000;
            const hasRequiredComment = comments.some(c => {
              const byCloser = c.user?.login === closer;
              const t = new Date(c.created_at).getTime();
              const closed = closedAt.getTime();
              return byCloser && Math.abs(t - closed) <= windowMs;
            });

            if (!hasRequiredComment) {
              await github.rest.issues.update({ owner, repo, issue_number, state: 'open' });
              await github.rest.issues.createComment({
                owner, 
                repo, 
                issue_number,
                body: 'Reopened: please leave a brief comment explaining the resolution before closing.'
              });
              core.setFailed('Issue closed without a qualifying comment; reopened.');
            } else {
              core.info('Qualifying comment found. Keeping issue closed.');
            }